Make TransformationRegistry immutable
KyoriPowered/adventure-text-minimessage pull request #122
Opened 2021-06-10 12:32 UTC by broccolai

Closes #119

2021-06-18 21:51 UTC, kashike requested changes

2021-06-18 21:51 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/MiniMessage.java
> +    @NotNull Builder transformationRegistry(final TransformationRegistry transformationRegistry);
```suggestion
    @NotNull Builder transformations(final TransformationRegistry transformationRegistry);
```

2021-06-18 21:51 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/transformation/TransformationRegistry.java
> +  TransformationRegistry STANDARD = TransformationRegistry.builder().build();
Move these to the impl class.

2021-06-18 21:51 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/transformation/TransformationRegistry.java
> +  boolean exists(String name, Function<String, ComponentLike> placeholderResolver);
make variables final

2021-06-18 21:51 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/transformation/TransformationRegistry.java
> +  @Nullable Transformation get(String name, List<TagPart> inners, Map<String, Template> templates, Function<String, ComponentLike> placeholderResolver, Context context);
make variables final

2021-06-22 20:43 UTC, merged

2021-06-22 20:43 UTC, MiniDigger commented
thanks!