Reversed Rainbow
KyoriPowered/adventure-text-minimessage pull request #152
Opened 2021-09-05 18:22 UTC by TreyRuffy

This PR changes the way you can create rainbows. If you use the `^` symbol (subject to change) you can create a rainbow which is an exact reversal of a rainbow with or without phase.

2021-09-05 18:27 UTC, kezz commented
Check the style issues, there's a gradle task you can run to validate it locally. Other than that, I like the idea of being able to reverse a rainbow.

2021-09-05 18:31 UTC, TreyRuffy commented
> Check the style issues, there's a gradle task you can run to validate it locally. Other than that, I like the idea of being able to reverse a rainbow.

Sounds good, just pushed the fix

2021-09-05 19:00 UTC, thiccaxe commented
Maybe look into `!` as opposed to `^`, it has more meaning because of its usage as not

2021-09-05 19:03 UTC, TreyRuffy commented
> Maybe look into `!` as opposed to `^`, it has more meaning because of its usage as not

I didn't even think of that. I'll leave the discussion open for a bit before changing it, but I think it's a much better symbol.

2021-09-05 19:24 UTC, kashike requested changes

2021-09-05 19:24 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/RainbowTransformation.java
> +        value = value.replace("^", "");
Reference a `static final String REVERSE` constant in this class instead, please.

2021-09-06 07:58 UTC, MiniDigger commented
I like this, could you create a PR for documenting this on the docs repo before we merge? https://github.com/KyoriPowered/adventure-docs

2021-09-07 20:29 UTC, kezz approved these changes
`!` is much better!

2021-09-27 15:21 UTC, MiniDigger commented
sorry in the delay handling this, I moved the REVERSE constant into the token class, but else looks good, thanks!

2021-09-27 15:22 UTC, merged