Allow explicitly setting decorations to false, closes #133
KyoriPowered/adventure-text-minimessage pull request #162
Opened 2021-09-28 20:10 UTC by MiniDigger

2021-09-28 20:10 UTC, MiniDigger commented
don't merge before a docs PR has been created...

2021-09-29 03:09 UTC, zml2008 requested changes, later dismissed
can you modify the serializer to emit `:false` decoration tags as well? that would make components more roundtrippable :)

2021-09-29 09:27 UTC, kezz commented
Does this handle closing as well? For example, would `<italic:false>Hello! <italic>spooky</italic> not spooky</italic:false>` work correctly as well? If so, might be worth throwing a test case for this in.

2021-12-02 21:18 UTC, kashike approved these changes

2021-12-03 16:38 UTC, MiniDigger commented
should be good to go, tried my best with the serializer but it just needs a complete rewrite

2021-12-03 21:51 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/parser/node/TagPart.java
> +    return "t".equals(this.value) || "true".equals(this.value) || "on".equals(this.value);
not a fan of `t`

2021-12-03 21:51 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/parser/node/TagPart.java
> +    return "f".equals(this.value) || "false".equals(this.value) || "off".equals(this.value);
not a fan of `f`

2021-12-04 12:07 UTC, kezz approved these changes
Serializer changes are a bit messy, but not an issue at all considering it'll be rewritten soon.

2021-12-06 09:33 UTC, kezz commented on src/main/java/net/kyori/adventure/text/minimessage/transformation/inbuild/DecorationTransformation.java
> +    boolean flag = args.size() != 1 || !args.get(0).isFalse();
Do we want to throw an error for bad arguments? For example, `<b:hello>` would be okay here.

2021-12-06 17:29 UTC, merged