fix: Recursively resolve string placeholders
KyoriPowered/adventure-text-minimessage pull request #187
Opened 2021-10-31 13:28 UTC by kezz

This PR is based on #186 (i don't like pre tags at all) and can be rebased after it is merged.

2021-10-31 18:04 UTC, zml2008 requested changes
few little things

for reference, the wip I had locally if you want to grab anything off it: https://paste.gg/p/anonymous/31331cbbc2824bec994cef7424307184

2021-10-31 18:04 UTC, zml2008 commented on src/main/java/net/kyori/adventure/text/minimessage/parser/TokenParser.java
> +    final String actualMessage = resolvePlaceholders(message, string -> tagNameChecker.test(string, false), templateResolver);
I'd kinda like to have this run on a mutable token stream rather than going back & forth between StringBuilders, but this is at least simpler

2021-10-31 18:14 UTC, rymiel commented on src/main/java/net/kyori/adventure/text/minimessage/parser/match/PlaceholderResolvingMatchedTokenConsumer.java
> +            this.builder.append(((Template.StringTemplate) template).value());
Related to #185, i suppose

2021-10-31 18:17 UTC, kezz commented on src/main/java/net/kyori/adventure/text/minimessage/parser/match/PlaceholderResolvingMatchedTokenConsumer.java
> +            this.builder.append(((Template.StringTemplate) template).value());
hmmm - i think we could add a util method for plain text templates that just internally resolves directly to a string component template? but yeah, i reckon using two types of templates internally (well, that and the dynamic one - do we even need that anymore?) might be enough

2021-11-19 17:13 UTC, Silthus commented
Will this also work for resolving recursive templates like this?

```yaml
formats:
  channel:
    type: mini-message
    format: "<channel_formatted><yellow><sender><gray>: <message>"
  channel_formatted:
    format: "<gold>[</gold><green><channel_name></green><gold>]</gold>"
  sender:
    format: "<hover:show_text:'<sender_hover>'><sender_vault_prefix><click:run_command:/schat message send <sender_name>><sender_vault_prefix><sender_name></click><sender_vault_suffix></hover>"
  sender_hover:
    format: |-
      <gray>Name: <yellow><sender_name>
      <gray><i>Click to send <yellow><sender_display_name></yellow> a message.
```

If I parse a `channel` template I get the following result: `<gold>[</gold><green><channel_name></green><gold>]</gold>&e<hover:show_text:'<sender_hover>'><sender_vault_prefix><click:run_command:/schat message send <sender_name>><sender_vault_prefix><sender_name></click><sender_vault_suffix></hover>&7: Hi`

Expected would be that all placeholders are resolved and colors as well.
This is the code I use to parse the template: https://github.com/sVoxelDev/sChat/blob/feature/21-custom-player-formatting/src/main/java/net/silthus/chat/formats/MiniMessageFormat.java#L51

And these are the resolvers used: https://github.com/sVoxelDev/sChat/blob/feature/21-custom-player-formatting/src/main/java/net/silthus/chat/formats/MiniMessageFormatTemplateResolver.java
https://github.com/sVoxelDev/sChat/blob/feature/21-custom-player-formatting/src/main/java/net/silthus/chat/Message.java#L206

2021-11-19 18:31 UTC, kezz commented
> Is there a SNAPSHOT publish of this branch somewhere that I can test?

No, but you can clone this branch, build it and install it into your local repo for use. In answer to your question, yes this PR allows the content of placeholders to impact the serialization of the remainder of the string.

2021-11-19 19:42 UTC, Silthus commented
Works perfectly 🚀 

Before:
![image](https://user-images.githubusercontent.com/755327/142682246-0e981946-a524-4dd4-8ff2-a093f61b8d15.png)

After:
![image](https://user-images.githubusercontent.com/755327/142682117-ef725b3c-ec07-4f03-a981-2de91fe147e2.png)

2021-12-02 21:17 UTC, kashike approved these changes

2021-12-06 02:40 UTC, zml2008 approved these changes

2021-12-06 08:55 UTC, merged