Convenience method on MiniMessage#parse() accepting Object varargs
KyoriPowered/adventure-text-minimessage pull request #58
Opened 2020-11-23 18:41 UTC by aecsocket

Fixes #57. Also added a test.

2020-11-23 18:44 UTC, kashike requested changes

2020-11-23 18:44 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/MiniMessageImpl.java
> +      } else if (rawValue instanceof Component) {
```suggestion
      } else if (rawValue instanceof ComponentLike) {
```

2020-11-23 18:44 UTC, kashike commented on src/main/java/net/kyori/adventure/text/minimessage/MiniMessageImpl.java
> +        value = (Component) rawValue;
```suggestion
        value = ((ComponentLike) rawValue).asComponent();
```

2020-11-23 19:34 UTC, kashike approved these changes

2020-11-24 18:26 UTC, MiniDigger commented
thank you very much, I manually merged it into #50, which will be the next version of minimessage
https://github.com/KyoriPowered/adventure-text-minimessage/commit/b6eea1c9a9b53d8608fb211c72ca718cf51403ba

2020-11-24 18:26 UTC, closed without merging